name: Changeset Pipeline

on:
  push:
    branches:
      - feature/**
    types: [closed]
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  setup-changeset:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Setup
      uses: ./.github/actions/setup
      with:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Create Release Pull Request
      id: changesets
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit: "New: Version Release"     
        title: "New: Published Packages"