name: Release Pipeline

on:
  push:
    branches:
      - release

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
        # registry-url: 'https://registry.npmjs.org'

    - name: Install pNPM
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Fetch Main Branch
      run: git fetch origin main

    - name: Create Changeset Release Pull Request
      id: changesets
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    # If project does not have changesets, then for now app will fail.
    - name: Check Changeset
      if: steps.changesets.outputs.hasChangesets == 'false'
      run: exit 1

    # Build Only the Packages that has changes detected or has its version updated.
    - name: NX Build Affected Packages
      run: pnpm affected:build
    
    - name: Modify Workspace File
      run: sed -e "s|'packages\/|'dist/packages|" pnpm-workspace.yaml > pnpm-new.yaml && mv pnpm-new.yaml pnpm-workspace.yaml

    - name: Publish
      run: pnpm -r publish --access public