name: Release Pipeline

on:
  push:
    pull_request: 
    - main

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Setup
      uses: ./.github/actions/setup
      with:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish Packages
      run: echo "Publish"

    - name: Set Version Tag
      id: lib-version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Release Tag
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## CHANGELOG
          Release Version v${{ steps.lib-version.outputs.VERSION }}
        tag_name: v${{ steps.lib-version.outputs.VERSION }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

        