name: Release

on:
  pull_request:
    branches:
      - main
    # types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    if: github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Test
      run: echo ${{ github.head_ref }}
