name: Reset NX Cache In Release Pipeline

on:
  workflow_dispatch:
    inputs:
      reset_cache:
        description: 'Set to true to reset nx cache in release pipeline'
        required: false
        default: 'false'

permissions:
  id-token: write
  contents: write

jobs:
  cache-reset:
    name: Reset NX Cache
    if: ${{ github.event.inputs.reset_cache == 'true' }}
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Setup
      uses: ./.github/actions/setup
      with:
        GITHUB_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        CACHE_KEY: release-pipeline

    - name: Reset Cache
      run: pnpm github-pipeline:reset