name: Release Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Setup
      uses: ./.github/actions/setup
      with:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    # If project does not have changesets, then for now app will fail.
    - name: Check Changeset
      if: steps.changesets.outputs.hasChangesets == 'false'
      run: exit 1

    # Update Version of Packages based on Configured Changeset Version
    - name: Changeset Version
      run: npx changeset version

    # Build Only the Packages that has changes detected or has its version updated.
    - name: NX Build Affected Packages
      run: pnpm affected:build

    - name: Commit Changesets Update
      run: |
        git config --local user.email "deejaygeroso@gmail.com"
        git config --local user.name "Deejay Geroso [BOT]"
        git add .
        git commit -m "Update: Changeset Version Applied"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    # Upload dist directory to be reused by publish job.
    - name: Upload dist Directory
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        
    - name: Setup
      uses: ./.github/actions/setup
      with:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    # Download dist directory generated from build job.
    - name: Download dist Directory
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Modify Workspace File
      run: sed -e "s|'packages\/|'dist/packages/|" pnpm-workspace.yaml > pnpm-new.yaml && mv pnpm-new.yaml pnpm-workspace.yaml

    - name: Publish
      run: npx changeset publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
