name: Release Pipeline

on:
  push:
    branches:
      - release

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Setup
      uses: ./.github/actions/setup

    # - name: Fetch Main Branch
    #   run: git fetch origin main

    # # If project does not have changesets, then for now app will fail.
    # - name: Check Changeset
    #   if: steps.changesets.outputs.hasChangesets == 'false'
    #   run: exit 1

    # # Update Version of Packages based on Configured Changeset Version
    # - name: Changeset Version
    #   run: npx changeset version

    # # Build Only the Packages that has changes detected or has its version updated.
    # - name: NX Build Affected Packages
    #   run: pnpm affected:build

    # Build Only the Packages that has changes detected or has its version updated.
    - name: NX Build Affected Packages
      run: pnpm ui:build:prod
    
    # - name: Commit changes
    #   run: |
    #     git config --local user.email "actions@github.com"
    #     git config --local user.name "GitHub Actions"
    #     git add .
    #     git commit -m "Commit message"
    
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: main

    # Upload dist directory to be reused by publish job.
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dist
    #     path: dist

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test-and-build
  #   steps:
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18.16.0'
  #       registry-url: 'https://registry.npmjs.org'

  #   # Download dist directory generated from build job.
  #   - name: Download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: dist
  #       path: dist

  #   - name: Install pNPM
  #     run: npm install -g pnpm